#ifndef HD2_content_hpp
#define HD2_content_hpp
#include "HD2_wb.hpp"
#include <vector>

const std::vector<std::string> WarbondsNameList={
    "standard",
    "borderlinejustice",
    "chemicalagents",
    "controlgroup",
    "cuttingedge",
    "democraticdetonation",
    "dustdevils",
    "forceoflaw",
    "freedomsflame",
    "mastersofceremony",
    "polarpatriots",
    "servantsoffreedom",
    "steeledveterans",
    "truthenforcers",
    "urbanlegends",
    "vipercommandos",
    "redactedregiment",
    "siegebreakers",
    "entrencheddivision",
    "exoexperts",
    "killzone",
    "halo",
    "supercitizen",
    "superstore"
};

const std::vector<Warbond> Warbonds={
    Warbond("standard",
        {"AR-23 Liberator","AR-23P Liberator Penetrator","R-63 Dilligence","R-63CS Dilligence Counter-Sniper","Plas-1 Scorcher","LAS-5 Scythe","SG-8 Punisher","SG-8S Punisher Slugger","SG-225 Breaker","SG-225SP Breaker Spray-and-pray","SMG-37 Defender"},
        {"P-2 Peacemaker","P-19 Redeemer"},
        {"G-3 Smoke","G-12 High Explosive","G-6 Frag","G-16 Impact"},
        {"MG-43 Machine Gun","M-105 Stalwart","MG-206 Heavy Machine Gun","RS-422 Railgun","APW-1 Anti-Material Rifle","GL-21 Grenade Launcher",
        "FLAM-40 Flamethrower","LAS-99 Quasar Cannon","LAS-98 Laser Cannon","ARC-3 Arc Thrower","EAT-17 Expendable Anti-Tank","MLS-4X Commando",
        "AC-8 Autocannon","RL-77 Airburst Rocket Launcher","FAF-14 Spear","Recoilless Rifle"}),
    Warbond("borderlinejustice",
        {"R-6 Deadeye"},
        {"LAS-58 Talon"},
        {"TED-63 Dynamite"},
        {}),
    Warbond("chemicalagents",
        {},
        {"P-11 Stim Pistol"},
        {"G-4 Gas"},
        {"TX-41 Sterilizer"}),
    Warbond("controlgroup",
        {"VG-70 Variable"},
        {},
        {"G-31 Arc"},
        {"PLAS-45 Epoch"}),
    Warbond("cuttingedge",
        {"ARC-12 Blitzer","SG-8 Punisher Plasma","LAS-16 Sickle"},
        {"Las-7 Dagger"},
        {"G-23 Stun"},
        {}),
    Warbond("democraticdetonation",
        {"BR-14 Adjudicator","Exploding Crossbow","R-36 Eruptor"},
        {"GP-31 Grenade Pistol"},
        {"G-123 Thermite"},
        {}),
    Warbond("dustdevils",
        {"AR-2 Coyote"},
        {},
        {"G7-Pineapple"},
        {"S-11 Speargun", "MS-11 Solo Silo", "EAT-700 Expendable Napalm"}),
    Warbond("forceoflaw",
        {"AR-32 Pacifier"},
        {"P-92 Warrant"},
        {"G-109 Urchin"},
        {"GL-52 De-Escalator"}),
    Warbond("freedomsflame",
        {"SG-451 Punisher Cookout","FLAM-66 Torcher"},
        {"P-72 Crisper"},
        {},
        {}),
    Warbond("mastersofceremony",
        {"R-2 Amendment"},
        {"CQC-2 Saber"},
        {"G-142 Pyrotech"},
        {"One True Flag"}),
    Warbond("polarpatriots",
        {"AR-61 Tenderizer","Plas-101 Purifier","SMG-72 Pummeler"},
        {"P-113 Verdict"},
        {"G-13 Incendiary Impact"},
        {}),
    Warbond("pythoncommandos",
        {"AR/GL-21 One-Two"},
        {},
        {},
        {"M-1000 Maxigun", "CQC-9 Defoliation Tool", "AX/FLAM-75 Hotdog"}),
    Warbond("servantsoffreedom",
        {"LAS-17 Double-Edge Sickle"},
        {"GP-20 Ultimatum","CQC-5 Combat Hatchet"},
        {"G-50 Seeker"},
        {}),
    Warbond("steeledveterans",
        {"JAR-5 Dominator","SG-225IE Breaker Incendiary","Liberator Concussive"},
        {"P-4 Senator"},
        {"G-10 Incendiary"},
        {}),
    Warbond("truthenforcers",
        {"SMG-32 Reprimand","SG-20 Halt"},
        {"Plas-15 Loyalist"},
        {},
        {}),
    Warbond("urbanlegends",
        {},
        {"CQC-30 Stun Baton","CQC-19 Stun Lance"},
        {},
        {}),
    Warbond("vipercommandos",
        {"Liberator Carbine"},
        {"SG-22 Bushwhacker"},
        {"K-2 Throwing Knife"},
        {}),
    Warbond("redactedregiment",
        {"R-72 Censor", "AR-59 Suppressor"},
        {"P-35 Re-Educator"},
        {"TM-01 Lure Mine"},
        {"B/MD C4 Pack"}),
    Warbond("siegebreakers",
        {"LAS-16 Trident"},
        {},
        {},
        {"CQC-20 Breaching Hammer", "EAT-411 Leveller", "GL-28 Belt-Fed Grenade Launcher"}),
    Warbond("entrencheddivision",
        {"SMG/FLAM-34 Stoker"},
        {"P-69 Veto", "CQC-73 Entrenchent Tool"},
        {"A/GM-17 Giga Grenade"},
        {"B/FLAM-80 Cremator"}),
    Warbond("exoexperts",
        {"SMG-203 Gallant"},
        {"P-33 Missile Pistol"},
        {},
        {"MGX-42 Bullet Storm"}),
    Warbond("supercitizen",
        {"MP-98 Knight"},
        {},
        {},
        {}),
    Warbond("killzone",
        {"StA-52 Assault Rifle","StA-11 SMG","PLAS-39 Accelerator Rifle"},
        {},
        {},
        {}),
    Warbond("halo",
        {"MA5C Assault Rifle","M90A Shotgun","M7S SMG"},
        {"M6C/SOCOM Pistol"},
        {},
        {}),
    Warbond("superstore",
        {"DBS-2 Double Freedom", "SG-97 Sweeper"},
        {"CQC-5 Combat Hatchet", "CQC-30 Stun Baton", "P-92 Warrant", "Machete"},
        {},
        {"StA-X3 W.A.S.P. Launcher"})
};
#endif